function Inertia_Matrix = A_tennisServe(in1,in2)
%A_TENNISSERVE
%    INERTIA_MATRIX = A_TENNISSERVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:48

Ic1 = in2(4,:);
Ic2 = in2(5,:);
Ic3 = in2(6,:);
l1 = in2(7,:);
l2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
r1 = in2(10,:);
r2 = in2(11,:);
r3 = in2(12,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th2);
t3 = cos(th3);
t4 = th2+th3;
t5 = l1.^2;
t6 = l2.^2;
t7 = r2.^2;
t8 = r3.^2;
t9 = cos(t4);
t10 = m3.*t6;
t11 = m2.*t7;
t12 = m3.*t8;
t13 = l1.*l2.*m3.*t2;
t14 = l1.*m2.*r2.*t2;
t15 = l2.*m3.*r3.*t3;
t16 = t15.*2.0;
t17 = l1.*m3.*r3.*t9;
t18 = Ic3+t12+t15;
t19 = t17+t18;
t20 = Ic2+Ic3+t10+t11+t12+t13+t14+t16+t17;
Inertia_Matrix = reshape([Ic1+t13+t14+t17+t20+m2.*t5+m3.*t5+m1.*r1.^2,t20,t19,t20,Ic2+Ic3+t10+t11+t12+t16,t18,t19,t18,Ic3+t12],[3,3]);
