function a3 = acceleration_endEffector(in1,in2)
%ACCELERATION_ENDEFFECTOR
%    A3 = ACCELERATION_ENDEFFECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:49

ddth1 = in1(7,:);
ddth2 = in1(8,:);
ddth3 = in1(9,:);
dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l1 = in2(7,:);
l2 = in2(8,:);
l3 = in2(9,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l1.*t2;
t6 = cos(t4);
t7 = l1.*t3;
t8 = sin(t4);
t9 = t4+th3;
t10 = cos(t9);
t11 = sin(t9);
t12 = l2.*t6;
t13 = l2.*t8;
t14 = l3.*t10;
t15 = l3.*t11;
t16 = dth3.*t14;
t17 = dth3.*t15;
t18 = t12+t14;
t19 = t13+t15;
t20 = dth2.*t18;
t21 = dth2.*t19;
t22 = t5+t18;
t23 = t7+t19;
a3 = [-dth3.*(t16+dth1.*t14+dth2.*t14)-ddth3.*t15-ddth2.*t19-ddth1.*t23-dth2.*(t16+t20+dth1.*t18)-dth1.*(t16+t20+dth1.*t22);-dth3.*(t17+dth1.*t15+dth2.*t15)+ddth3.*t14+ddth2.*t18+ddth1.*t22-dth2.*(t17+t21+dth1.*t19)-dth1.*(t17+t21+dth1.*t23)];
