function Corr_Terms = Corr_Terms(in1,in2)
%CORR_TERMS
%    CORR_TERMS = CORR_TERMS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:50

dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l1 = in2(7,:);
l2 = in2(8,:);
m2 = in2(2,:);
m3 = in2(3,:);
r2 = in2(11,:);
r3 = in2(12,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = sin(th2);
t3 = sin(th3);
t4 = th2+th3;
t5 = dth1.^2;
t6 = dth2.^2;
t7 = dth3.^2;
t8 = sin(t4);
t9 = l2.*m3.*r3.*t3.*t7;
t10 = dth1.*dth3.*l2.*m3.*r3.*t3.*2.0;
t11 = dth2.*dth3.*l2.*m3.*r3.*t3.*2.0;
t12 = -t10;
t13 = -t11;
t14 = -t9;
Corr_Terms = [t12+t13+t14-l1.*l2.*m3.*t2.*t6-l1.*m2.*r2.*t2.*t6-l1.*m3.*r3.*t6.*t8-l1.*m3.*r3.*t7.*t8-dth1.*dth2.*l1.*l2.*m3.*t2.*2.0-dth1.*dth2.*l1.*m2.*r2.*t2.*2.0-dth1.*dth2.*l1.*m3.*r3.*t8.*2.0-dth1.*dth3.*l1.*m3.*r3.*t8.*2.0-dth2.*dth3.*l1.*m3.*r3.*t8.*2.0;t12+t13+t14+l1.*l2.*m3.*t2.*t5+l1.*m2.*r2.*t2.*t5+l1.*m3.*r3.*t5.*t8;m3.*r3.*(l2.*t3.*t5+l2.*t3.*t6+l1.*t5.*t8+dth1.*dth2.*l2.*t3.*2.0)];
