function E = energy_tennisServe(in1,in2)
%ENERGY_TENNISSERVE
%    E = ENERGY_TENNISSERVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:49

Ic1 = in2(4,:);
Ic2 = in2(5,:);
Ic3 = in2(6,:);
dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
g = in2(13,:);
k1 = in2(14,:);
k2 = in2(15,:);
k3 = in2(16,:);
l1 = in2(7,:);
l2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
r1 = in2(10,:);
r2 = in2(11,:);
r3 = in2(12,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = dth1.^2;
t6 = r1.^2;
t7 = l1.*t2;
t8 = cos(t4);
t9 = l1.*t3;
t10 = sin(t4);
t11 = t4+th3;
t12 = cos(t11);
t13 = sin(t11);
t14 = l2.*t8;
t15 = l2.*t10;
t16 = r2.*t10;
t17 = r3.*t13;
t18 = r3.*t12;
t19 = t9+t16;
t20 = t9+t15+t17;
E = (Ic1.*t5)./2.0+(Ic2.*(dth1+dth2).^2)./2.0+(m1.*(t2.^2.*t5.*t6+t3.^2.*t5.*t6))./2.0+(Ic3.*(dth1+dth2+dth3).^2)./2.0+(k1.*th1.^2)./2.0+(k2.*th2.^2)./2.0+(k3.*th3.^2)./2.0+(m2.*((dth2.*t16+dth1.*t19).^2+(dth1.*(t7+r2.*t8)+dth2.*r2.*t8).^2))./2.0+(m3.*((dth2.*(t15+t17)+dth3.*t17+dth1.*t20).^2+(dth2.*(t14+t18)+dth3.*t18+dth1.*(t7+t14+t18)).^2))./2.0+g.*m2.*t19+g.*m3.*t20+g.*m1.*r1.*t3;
