function Grav_Terms = Grav_Terms(in1,in2)
%GRAV_TERMS
%    GRAV_TERMS = GRAV_TERMS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:50

g = in2(13,:);
l1 = in2(7,:);
l2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
r1 = in2(10,:);
r2 = in2(11,:);
r3 = in2(12,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = l1.*t2;
t5 = cos(t3);
t6 = t3+th3;
t7 = cos(t6);
t8 = l2.*t5;
t9 = r3.*t7;
Grav_Terms = [g.*m2.*(t4+r2.*t5)+g.*m3.*(t4+t8+t9)+g.*m1.*r1.*t2;g.*m3.*(t8+t9)+g.*m2.*r2.*t5;g.*m3.*t9];
