function keypoints = keypoints_tennisServe(in1,in2)
%KEYPOINTS_TENNISSERVE
%    KEYPOINTS = KEYPOINTS_TENNISSERVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:50

l1 = in2(7,:);
l2 = in2(8,:);
l3 = in2(9,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l1.*t2;
t6 = cos(t4);
t7 = l1.*t3;
t8 = sin(t4);
t9 = t4+th3;
t10 = l2.*t6;
t11 = l2.*t8;
keypoints = reshape([t5,t7,t5+t10,t7+t11,t5+t10+l3.*cos(t9),t7+t11+l3.*sin(t9)],[2,3]);
