function Stiffness_Matrix = Stiffness_Matrix(in1,in2)
%STIFFNESS_MATRIX
%    STIFFNESS_MATRIX = STIFFNESS_MATRIX(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:50

k1 = in2(14,:);
k2 = in2(15,:);
k3 = in2(16,:);
Stiffness_Matrix = reshape([k1,0.0,0.0,0.0,k2,0.0,0.0,0.0,k3],[3,3]);
