function v3 = velocity_endEffector(in1,in2)
%VELOCITY_ENDEFFECTOR
%    V3 = VELOCITY_ENDEFFECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 20:09:49

dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l1 = in2(7,:);
l2 = in2(8,:);
l3 = in2(9,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+th3;
t6 = cos(t5);
t7 = sin(t5);
t8 = l2.*t3;
t9 = l2.*t4;
t10 = l3.*t6;
t11 = l3.*t7;
v3 = [-dth2.*(t9+t11)-dth3.*t11-dth1.*(t9+t11+l1.*sin(th1));dth2.*(t8+t10)+dth3.*t10+dth1.*(t8+t10+l1.*cos(th1))];
